// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Carnation
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCarnationPackageString = "2cc0a490-70eb-4dd6-a16e-a29b8f3d273c";
        public static Guid guidCarnationPackage = new Guid(guidCarnationPackageString);

        public const string guidCarnationPackageCmdSetString = "a432b46a-d8e0-4439-bd9e-58e40c02453c";
        public static Guid guidCarnationPackageCmdSet = new Guid(guidCarnationPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainWindowCommandId = 0x0100;
    }
}